name: Build and test compiler on Ubuntu

on:
  push:
    branches: ["*"]
    paths:
      - "ecli/**"
      - "compiler/**"  # Ensure ecc and ecli releasing at same time
      - "wasm-rumtime/**"  # Release when dependencies updated
      - "third_party/**"
      - "bpf-loader/**"
      - "eunomia-sdk/**"
      - ".github/**"

  pull_request:
    branches: ["*"]
    paths:
      - "ecli/**"
      - "compiler/**"
      - "wasm-rumtime/**"
      - "third_party/**"
      - "bpf-loader/**"
      - "eunomia-sdk/**"
      - ".github/**"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]


    steps:
    - uses: actions/checkout@v2

    - name: get submodule
      run:  git submodule update --init --recursive --remote

    - name: install deps
      run: |
          sudo make -C compiler install-deps
          cargo install clippy-sarif sarif-fmt grcov
          rustup component add llvm-tools-preview

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: build ecc
      run:  cd compiler && make && make install

    - name: test ecc
      run:  cd compiler && make test
    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: compiler/cmd/rust-clippy-results.sarif
        wait-for-processing: true

    - name: Code coverage using Codecov
      run: bash <(curl -s https://codecov.io/bash)

      # All scripts below only run while pushing to master branch.
    - name: Set latest release version
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: set_version
      uses: actions/github-script@v3
      with:
        result-encoding: string
        script: |

          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          async function get_release_commit_sha(release) {
          
            const { data: release_commit } = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: release.target_commitish,
            });
            console.log("release commit sha:" + release_commit[0].sha);
            return release_commit[0].sha;
          }
          
          if (releases.length === 0) { return "v0.0.1"; }
          
          async function getReleaseForCommitSha(commitSha) {
            const { owner, repo } = context.repo;
            const { data: releases } = await github.repos.listReleases({ owner, repo });
            return releases.find(release =>  get_release_commit_sha(release) === commitSha );
          }
          
          function increase_v(version) {
            const parts = version.split(".");
            const last = parseInt(parts[2]) + 1;
            const next_version = `${parts[0]}.${parts[1]}.${last.toString()}`;
            return next_version;
          }
          
          console.log("now context.sha: " + context.sha);
          const coresp_release = await getReleaseForCommitSha(context.sha);
          const latest_release_tag = releases[0].tag_name;
          console.log("coresp_release: " + coresp_release);
          console.log("latest_release_tag: " + latest_release_tag);
          
          if (coresp_release === undefined) {
            return increase_v(latest_release_tag)
          }
          
          const coresp_release_tag = coresp_release.tag_name;
          
          console.log("coresponding release tag is: " + coresp_release_tag)
          console.log("SHA of this commit: " + sha)
          
          return latest_release_tag      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Package
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      shell: bash
      run: |
        mkdir release
        cp compiler/workspace/bin/ecc ./release/
        cd release
        tar czvf ./ecc-${{ matrix.target }}-${{ steps.set_version.outputs.result }}.tar.gz ecc

    - name: Publish
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
          files: |
            release/ecc-${{ matrix.target }}-${{ steps.set_version.outputs.result }}.tar.gz
          prerelease: false
          tag_name: ${{ steps.set_version.outputs.result }}
          generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 