name: test CI 1

on:
  push:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]

    steps:
    - uses: actions/checkout@v2

      # All scripts below only run while pushing to master branch.
    - name: Set latest release version
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: set_version
      uses: actions/github-script@v6
      
      with:
        result-encoding: string
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const { data: tags } = await github.rest.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          if (releases.length === 0) { return "v0.0.1"; }
          
          
          function increase_v(version) {
            const parts = version.split(".");
            const last = parseInt(parts[2]) + 1;
            const next_version = `${parts[0]}.${parts[1]}.${last.toString()}`;
            return next_version;
          }
          
          const latest_release_tag = releases[0].tag_name;
          
          const tag = tags.find(tag => tag.commit.sha === context.sha);
          
          if (tag) {
            console.log("exist coresponding tag: " + tag);
            return tag;
          }
          
          console.log("tag not found, will create" + increase_v(tag));
          
          return increase_v(tag);
          
          
    - name: echo
      shell: bash
      run: |
        echo "${{ steps.set_version.outputs.result }}"

      
    - name: Package
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      shell: bash
      run: |
        sleep 30
        touch test-1
        echo "aba" > test-1

    - name: Publish
      if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
          files: |
            ./test-1
          prerelease: false
          tag_name: ${{ steps.set_version.outputs.result }}
          generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
